### PR TITLE
Created HUD system

### PR DESCRIPTION
**Pull request by KingsMMA**
HUD system to easily create new elements and render them without having to do messy and repetitive rendering, configuration, and customisation code for each new HUD element

Ignore first two commits

### CODE REVIEW

**Comment by KingsMMA** [comment]
I still need to add more features and convert existing elements to using the system.
Please don't merge this PR yet.

**Comment by KingsMMA** [comment]
New HUD system is essentially done; all I need to do is save the GUI locations

**Comment by MrSam7K** [comment]
Game crashes if you click this button
image
from title screen and not from ESC -> Options > BunnyUtils

**Comment by KingsMMA** [comment]
> Game crashes if you click this button image from title screen and not from ESC -> Options > BunnyUtils

I can't recreate this issue.
I've applied a potential fix in the following commit, can you please send me the crash log if it isn't fixed

**Comment by MrSam7K** [comment]
> > Game crashes if you click this button image from title screen and not from ESC -> Options > BunnyUtils
> 
> I can't recreate this issue. I've applied a potential fix in the following commit, can you please send me the crash log if it isn't fixed

Alright, so it happens to work with new changes I committed and yes it's my fault that it was happening. Fixed them

**Comment by MrSam7K** [comment]
I can't seem to figure out how to make `intSlider` (from Config class) change background opacity of overlays. I've added `hex` int in HudRenderer so maybe you can add that.

**Comment by KingsMMA** [comment]
What still needs to be done?
Can this be merged @MrSam7K?

**Pull request merged**
